version: "3.7"
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vuttr
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    container_name: db    
    environment:
      - POSTGRES_DB=vuttr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - TZ=GMT
    restart: always    
    ports:
      - "5432:5432"
      
  
    
     